-- 1. Habilitar la tabla de perfiles para guardar info extra de los usuarios
CREATE TABLE profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email TEXT NOT NULL,
  full_name TEXT,
  role TEXT DEFAULT 'swimmer', -- 'admin' o 'swimmer'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 2. Asegurar que la tabla swim_plans exista
CREATE TABLE IF NOT EXISTS swim_plans (
  user_id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  plan_data JSONB NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

-- 3. Habilitar Row Level Security (RLS)
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE swim_plans ENABLE ROW LEVEL SECURITY;

-- 4. Políticas para PROFILES
-- Los usuarios pueden leer su propio perfil
CREATE POLICY "Users can view own profile" ON profiles FOR SELECT USING (auth.uid() = id);
-- Los admins pueden ver todos los perfiles
CREATE POLICY "Admins can view all profiles" ON profiles FOR SELECT USING (
  (auth.jwt() ->> 'email') = 'admin@admin.com'
);

-- 5. Políticas para SWIM_PLANS
-- Los usuarios pueden ver y editar su propio plan
CREATE POLICY "Users can manage own plan" ON swim_plans FOR ALL USING (auth.uid() = user_id);
-- Los admins pueden ver todos los planes
CREATE POLICY "Admins can view all plans" ON swim_plans FOR SELECT USING (
  (auth.jwt() ->> 'email') = 'admin@admin.com'
);

-- 6. Tabla para almacenar las mediciones de tiempo individuales
CREATE TABLE IF NOT EXISTS measurements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES auth.users ON DELETE CASCADE NOT NULL,
  date DATE NOT NULL,
  time_string TEXT NOT NULL, -- "MM:SS.CC"
  seconds NUMERIC NOT NULL,   -- Valor convertido para gráficas
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW())
);

ALTER TABLE measurements ENABLE ROW LEVEL SECURITY;

-- Los usuarios pueden gestionar sus propias mediciones
CREATE POLICY "Users can manage own measurements" ON measurements FOR ALL USING (auth.uid() = user_id);
-- Los admins pueden ver todas las mediciones
CREATE POLICY "Admins can view all measurements" ON measurements FOR SELECT USING (
  (auth.jwt() ->> 'email') = 'admin@admin.com'
);

-- 7. Trigger para crear un perfil automáticamente cuando se registra un usuario
-- Nota: El primer usuario que se registre debería ser cambiado a 'admin' manualmente en la tabla.
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger AS $$
BEGIN
  INSERT INTO public.profiles (id, email, role)
  VALUES (new.id, new.email, 'swimmer');
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
